src/BookReviewer/Models/Users/BecomeAnAuthorFormModel.cs
namespace BookReviewer.Models.Users
{
    public class BecomeAnAuthorFormModel
    {
        public string Name { get; init; }

        public string DateOfBirth { get; init; }

        public string Details { get; init; }

        public string PictureUrl { get; init; }
    }
}

src/BookReviewer/Models/Users/UserAddBookFormModel.cs
namespace BookReviewer.Models.Users
{
    using BookReviewer.Models.Books;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class UserAddBookFormModel
    {
        public string Title { get; init; }

        public string Author { get; init; }

        public string CoverUrl { get; init; }

        public string YearPublished { get; init; }

        public int Pages { get; init; }

        public string Description { get; init; }

        [Display(Name = "Genres")]
        public ICollection<string> BookGenres { get; init; }
        public IEnumerable<string> Genres { get; set; }
    }
}

src/BookReviewer/Controllers/BooksController.cs
namespace BookReviewer.Controllers
{
    using BookReviewer.Data;
    using BookReviewer.Models.Books;
    using BookReviewer.Services.Books;
    using BookReviewer.Infrastructure;
    using BookReviewer.Services.Genres;
    using BookReviewer.Services.Authors;

    using System.Linq;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    public class BooksController : Controller
    {
        private readonly IBookService books;
        private readonly BookReviewerDbContext data;
        private readonly IGenreService genres;
        private readonly IAuthorService authors;
        private readonly IMapper mapper;

        public BooksController(IBookService books,
            BookReviewerDbContext data,
            IGenreService genres,
            IAuthorService authors,
            IMapper mapper)
        {
            this.books = books;
            this.data = data;
            this.genres = genres;
            this.authors = authors;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Add()
        {
            if (!this.authors.IsAuthor(User.Id()))
            {
                return RedirectToAction("Add", "Authors");
            }

            return View(new BookFormModel
            {
                Genres = this.genres.GetGenres()
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(BookFormModel book)
        {
            if (!ModelState.IsValid)
            {
                book.Genres = this.genres.GetGenres();

                return View(book);
            }

            var currentUser = this.data.Users
                .FirstOrDefault(u => u.Id == User.Id());

            this.books.UserCreate(currentUser, book);

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult Edit(string id)
        {
            if (!this.authors.IsAuthorOfBook(User.Id(), id) && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var book = this.books.BookDetails(id);

            var editBookForm = this.mapper.Map<BookFormModel>(book);
            editBookForm.Genres = this.genres.GetGenres();

            return View(editBookForm);
        }

        [HttpPost]
        public IActionResult Edit(string id, BookFormModel editedBook)
        {
            if (!ModelState.IsValid)
            {
                editedBook.Genres = this.genres.GetGenres();

                return View(editedBook);
            }

            this.books.Edit(id, editedBook);

            return Redirect($"/Books/Details/{id}");
        }

        public IActionResult Details(string id) => View(books.BookDetails(id));

        public IActionResult Search(string searchTerm, string genre)
        {
            if (this.books.SearchBooks(searchTerm, genre) == null)
            {
                return Redirect("/");
            }

            return View((this.books.SearchBooks(searchTerm, genre)));
        }
    }
}

src/BookReviewer/Controllers/ListsController.cs
namespace BookReviewer.Controllers
{
    using BookReviewer.Infrastructure;
    using BookReviewer.Models.Lists;
    using BookReviewer.Services.Lists;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ListsController : Controller
    {
        private readonly IListService lists;

        public ListsController(IListService lists)
        {
            this.lists = lists;
        }

        public IActionResult UserLists(string id) => View(this.lists.GetUserLists(id));

        [Authorize]
        public IActionResult Create() => View();

        [Authorize]
        [HttpPost]
        public IActionResult Create(ListFormModel form)
        {
            if (!ModelState.IsValid)
            {
                return View(form);
            }

            var createdListId = this.lists.Create(User.Id(), form);

            return Redirect($"/Lists/Edit/{createdListId}");
        }

        public IActionResult Details(string id)
        {
            var details = this.lists.GetListDetails(id);

            return View(details);
        }

        [Authorize]
        public IActionResult Edit(string id)
        {
            if (!this.lists.UserOwnsList(User.Id(), id) && !User.IsAdmin()) 
            {
                return Redirect("/Home/Error");
            }

            var details = this.lists.GetListDetails(id);

            return View(details);
        }

        [Authorize]
        public IActionResult Delete(string id)
        {
            if (!this.lists.UserOwnsList(User.Id(), id) && !User.IsAdmin())
            {
                return Redirect("/Home/Error");
            }

            this.lists.Delete(id);

            return Redirect($"/Users/Profile/{User.Id()}");
        }

        [Authorize]
        public IActionResult AddToList(string id)
        {
            var ids = id.Split("%2F");
            var bookId = ids[0];
            var listId = ids[1];

            if (!this.lists.UserOwnsList(User.Id(), listId) && !User.IsAdmin())
            {
                return Unauthorized();
            }

            this.lists.AddBook(bookId, listId);

            return Redirect($"/Lists/Edit/{listId}");
        }

        [Authorize]
        public IActionResult RemoveFromList(string id)
        {
            var ids = id.Split("%2F");
            var bookId = ids[0];
            var listId = ids[1];

            if (!this.lists.UserOwnsList(User.Id(), listId) && !User.IsAdmin())
            {
                return Unauthorized();
            }

            this.lists.RemoveBook(bookId, listId);

            return Redirect($"/Lists/Edit/{listId}");
        }
    }
}

src/BookReviewer/Controllers/ReviewsController.cs
namespace BookReviewer.Controllers
{
    using BookReviewer.Models.Reviews;
    using BookReviewer.Services.Reviews;
    using BookReviewer.Infrastructure;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    public class ReviewsController : Controller
    {
        private readonly IReviewService reviews;

        public ReviewsController(IReviewService reviews)
        {
            this.reviews = reviews;
        }

        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(string id, ReviewFormModel review)
        {
            if (!ModelState.IsValid)
            {
                return View(review);
            }

            this.reviews.Create(id,User.Id(), review);

            return Redirect($"/Books/Details/{id}");
        }

        [Authorize]
        public IActionResult Edit(string id)
        {
            if (!this.reviews.UserOwnsReview(User.Id(), id) && !User.IsAdmin())
            {
                return Redirect("/Home/Error");
            }

            return View(this.reviews.Details(id));
        }


        [Authorize]
        [HttpPost]
        public IActionResult Edit(string id, ReviewFormModel editedReview)
        {
            var currentUserId = User.Id();

            this.reviews.Edit(id, editedReview);

            return Redirect($"/Reviews/UserReviews/{currentUserId}");
        }

        [Authorize]
        public IActionResult Delete(string id)
        {
            if (!this.reviews.UserOwnsReview(User.Id(), id) && !User.IsAdmin())
            {
                return Redirect("/Home/Error");
            }

            var userId = User.Id();

            this.reviews.Delete(id);

            return Redirect($"/Reviews/UserReviews/{userId}");
        }

        public IActionResult UserReviews(string id) => View(this.reviews.GetUserReviews(id));
    }
}

src/BookReviewer/Controllers/UsersController.cs
namespace BookReviewer.Controllers
{
    using BookReviewer.Models.Users;
    using BookReviewer.Services.Users;

    using Microsoft.AspNetCore.Mvc;

    public class UsersController : Controller
    {
        private readonly IUserService users;

        public UsersController(IUserService users)
        {
            this.users = users;
        }

        public IActionResult Profile(string id) => View(users.Profile(id));

        public IActionResult ChangeProfilePicture(string id) => View();

        [HttpPost]
        public IActionResult ChangeProfilePicture(string id, ChangeProfilePictureFormModel profilePic)
        {
            if (!ModelState.IsValid)
            {
                return View(profilePic);
            }

            this.users.ChangeProfilePicture(id, profilePic);

            return Redirect($"/Users/Profile/{id}");
        }
    }
}

src/BookReviewer/Views/Users/AddBook.cshtml
@model BookFormModel

@{
    ViewData["Title"] = "Add Book | ";
}

<h2>Add Book</h2>

<partial name="_BookFormPartial" model="Model"/>

src/BookReviewer/Views/Users/BecomeAnAuthor.cshtml
@model AuthorFormModel

@{
    ViewData["Title"] = "Become an author | ";
}

<h2>Become an author</h2>

<partial name="_AuthorFormPartial" model="Model"/>

src/BookReviewer/Views/Users/ChangeProfilePicture.cshtml
@model ChangeProfilePictureFormModel

<div class="d-flex justify-content-center">
    <h4>Change profile picture</h4>
</div>

<form method="post" class="mt-4">
    <div class="form-group">
        <label asp-for="PictureUrl"></label>
        <input asp-for="PictureUrl" class="form-control">
        <span asp-validation-for="PictureUrl" class="small text-danger"></span>
    </div>
    <button type="submit" class="btn btn-dark">Submit</button>
</form>

src/BookReviewer/Views/Users/EditAuthorDetails.cshtml
@model AuthorFormModel

@{
    ViewData["Title"] = "Edit author details | ";
}

<h2>Edit author details</h2>

<partial name="_AuthorFormPartial" model="Model" />

src/BookReviewer/Views/Users/EditBookDetails.cshtml
@model BookFormModel

@{
    ViewData["Title"] = "Edit Book | ";
}

<h2>Edit Book</h2>

<partial name="_BookFormPartial" model="Model" />

src/BookReviewer/Views/Users/EditReview.cshtml
@model ReviewFormModel

@{
    ViewData["Title"] = "Edit Review | ";
}

<h2>Edit Review</h2>

<partial name="_ReviewFormPartial" model="Model" />

src/BookReviewer/Views/Users/Profile.cshtml
@model UserProfileViewModel

@using BookReviewer.Infrastructure
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager

<section class="py-5">
    <div class="container">
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-6 text-center">
                <h2 class="display-5 fw-bolder">@Model.Username</h2>
                <img class="mb-5 mt-4 mb-md-0" src="@Model.ProfilePictureUrl" alt="..." height="250" width="250" />

                @if (SignInManager.IsSignedIn(User))
                {
                    @if (User.Id() == Model.Id)
                    {
                        <div class="text-center">
                            <a asp-controller="Users" asp-action="ChangeProfilePicture" asp-route-id="@Model.Id" class="mt-3">Change profile picture</a>
                        </div>
                    }
                }

            </div>
            <div class="col text-center">
                <div>
                    <a style="font-size: 4em" asp-controller="Reviews" asp-action="UserReviews" asp-route-id="@Model.Id">Reviews</a>
                </div>
                <div>
                    <a style="font-size: 4em" asp-controller="Lists" asp-action="UserLists" asp-route-id="@Model.Id">Lists</a>
                </div>

                @if (Model.AuthorId != null)
                {
                    <div>
                        <a style="text-decoration:solid; font-size: 4em" asp-controller="Authors" asp-action="Details" asp-route-id="@Model.AuthorId">Author page</a>
                    </div>

                }

            </div>
        </div>
    </div>
</section>

src/BookReviewer/Views/Users/Reviews.cshtml
@model AllReviewsViewModel

@using Microsoft.AspNetCore.Identity
@using BookReviewer.Infrastructure 

@inject UserManager<User> UserManager

@if (!Model.Reviews.Any())
{
    <h4>No reviews yet</h4>
}
else
{
    foreach (var review in Model.Reviews.OrderByDescending(r => r.DateAdded))
    {
        <div class="row mb-4" style="border:ridge">
            <img class="ml-2 mt-2 mb-2" src="@review.Book.CoverUrl" alt="..." height="150" width="100" />
            <div class="mb-3 mt-3 ml-3">
                <a asp-controller="Books" asp-action="Details" asp-route-id="@review.BookId" class="display-5 fw-bolder">@review.Book.Title</a>
                <span class="text-decoration-line-through">by</span>
                <a asp-controller="Authors" asp-action="Details" asp-route-id="@review.Book.AuthorId">@review.Book.Author.Name</a>
                <p class="mt-2">@review.User.UserName rated it @review.Stars.ToString() stars</p>

                @if (@review.Text != null)
                {
                    <p>@review.Text</p>
                }

                @if (User.Id() == review.UserId)
                {
                    <p>
                        <a class="btn btn-warning" asp-controller="Reviews" asp-action="Edit" asp-route-id="@review.Id">Edit</a>
                        <a class="btn btn-danger" asp-controller="Reviews" asp-action="Delete" asp-route-id="@review.Id">Delete</a>
                    </p>
                }
            </div>
        </div>
    }
}